try{
    add ("Welcome guest");
}
catch(err){
console.log(err.message)
}
try{
    multiply ("Welcome guest");
}
catch(err){
console.log(err.message)
}